spring:
  application:
    name: focus-flow-backend
  datasource:
    url: jdbc:postgresql://ep-silent-paper-a4frcx90.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_j1CrWTpf5maD
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

